# 资产数据及参数配置

# 欢迎语
welcome_text: |
  欢迎来到金融性格与模拟投资！在这里您将通过测试得到自己的金融性格，并获得100000体验金，可将其以任意比例配置在以下基金上。体验金会根据基金在市场上的真实涨跌而产生盈亏，一周后余额将以10000:1的比例兑换为投资红包！点击阅读基金的信息并配置资金。

# 更新为公募基金产品
assets:
  货币基金-余额宝:
    expected_return: 0.025
    risk: 0.005
    description: 低风险低回报，流动性极高，可随时取用，适合现金管理
  短债基金-建信短债:
    expected_return: 0.035
    risk: 0.02
    description: 低风险中低回报，投资于短期债券，流动性好，波动较小
  中长债基金-易方达中债:
    expected_return: 0.045
    risk: 0.05
    description: 中低风险中等回报，投资于各类国债、企债等，获取稳定收益
  混合基金-南方成长:
    expected_return: 0.065
    risk: 0.12
    description: 中等风险中高回报，股债混合配置，兼顾收益与安全性
  股票基金-易方达上证50:
    expected_return: 0.085
    risk: 0.18
    description: 高风险高回报，跟踪上证50指数，投资于大型蓝筹股票
  创业板基金-华夏创业板ETF:
    expected_return: 0.095
    risk: 0.22
    description: 高风险高回报，投资于创业板成长型企业，波动较大

# 资产名称翻译
asset_names_en:
  货币基金-余额宝: "Money Market Fund"
  短债基金-建信短债: "Short-term Bond Fund"
  中长债基金-易方达中债: "Medium-Long Bond Fund"
  混合基金-南方成长: "Mixed Fund"
  股票基金-易方达上证50: "Stock Index Fund"
  创业板基金-华夏创业板ETF: "Growth Stock Fund"

# 资产描述翻译
asset_descriptions_en:
  货币基金-余额宝: "Low risk with low returns, highly liquid, ideal for cash management"
  短债基金-建信短债: "Low risk with moderate-low returns, invests in short-term bonds"
  中长债基金-易方达中债: "Medium-low risk with moderate returns, invests in government and corporate bonds"
  混合基金-南方成长: "Medium risk with medium-high returns, mixed allocation of stocks and bonds"
  股票基金-易方达上证50: "High risk with high returns, tracks SSE 50 Index, invests in blue-chip stocks"
  创业板基金-华夏创业板ETF: "High risk with high returns, invests in growth companies on ChiNext board"

# 风险评分对应的资产配置推荐
risk_recommendations:
  very_conservative:  # 风险评分 < 20
    货币基金-余额宝: 0.50
    短债基金-建信短债: 0.30
    中长债基金-易方达中债: 0.15
    混合基金-南方成长: 0.05
    股票基金-易方达上证50: 0.00
    创业板基金-华夏创业板ETF: 0.00
  conservative:  # 风险评分 < 40
    货币基金-余额宝: 0.30
    短债基金-建信短债: 0.30
    中长债基金-易方达中债: 0.20
    混合基金-南方成长: 0.15
    股票基金-易方达上证50: 0.05
    创业板基金-华夏创业板ETF: 0.00
  moderate:  # 风险评分 < 60
    货币基金-余额宝: 0.15
    短债基金-建信短债: 0.20
    中长债基金-易方达中债: 0.25
    混合基金-南方成长: 0.20
    股票基金-易方达上证50: 0.15
    创业板基金-华夏创业板ETF: 0.05
  aggressive:  # 风险评分 < 80
    货币基金-余额宝: 0.05
    短债基金-建信短债: 0.10
    中长债基金-易方达中债: 0.15
    混合基金-南方成长: 0.30
    股票基金-易方达上证50: 0.25
    创业板基金-华夏创业板ETF: 0.15
  very_aggressive:  # 风险评分 >= 80
    货币基金-余额宝: 0.00
    短债基金-建信短债: 0.05
    中长债基金-易方达中债: 0.10
    混合基金-南方成长: 0.20
    股票基金-易方达上证50: 0.35
    创业板基金-华夏创业板ETF: 0.30

# 风险评分映射
risk_mapping:
  q1:
    不能接受亏损: 0
    最多5%: 20
    最多10%: 40
    最多20%: 60
    最多30%: 80
    30%以上: 100
  q2:
    立即全部卖出: 0
    卖出一部分: 33
    不采取行动: 67
    买入更多: 100
  q3:
    保本型产品: 0
    低风险理财产品: 25
    混合型基金: 50
    股票型基金: 75
    个股: 100
  q4:
    保持资本价值: 0
    获得高于通胀的稳定回报: 25
    适度资本增长: 50
    显著资本增长: 75
    积极资本增长: 100
  q5:
    1年以下: 0
    1-3年: 25
    3-5年: 50
    5-10年: 75
    10年以上: 100

# 风险偏好类型
risk_categories:
  very_conservative:
    max_score: 20
    name: 非常保守型
  conservative:
    max_score: 40
    name: 保守型
  moderate:
    max_score: 60
    name: 平衡型
  aggressive:
    max_score: 80
    name: 进取型
  very_aggressive:
    max_score: 100
    name: 激进型

# 行为测试问题
behavior_questions:
  风险厌恶:
    question: 在面对不同的投资选择时，您更倾向于：
    options:
      选择风险较小但收益也较低的稳定投资: 高
      选择风险适中且收益适中的平衡投资: 中
      选择风险较高但有可能带来高收益的投资: 低
  损失厌恶:
    question: 当您的投资发生亏损时，您的感受是：
    options:
      非常痛苦，亏损带来的负面感受远大于等额收益带来的正面感受: 高
      有些不适，但能够理性看待: 中
      能够坦然面对，视为投资过程的正常波动: 低
  心理账户:
    question: 对于不同来源的钱（比如工资、奖金、礼金），您会：
    options:
      对不同来源的钱有不同的使用计划和风险偏好: 高
      部分区分不同来源的钱的用途: 中
      不区分钱的来源，统一管理所有资金: 低
  过度自信:
    question: 对于自己的投资决策能力，您认为：
    options:
      我非常了解市场，相信自己的判断优于大多数人: 高
      我对某些领域有一定理解，但知道自己的局限性: 中
      我承认市场难以预测，不盲目相信自己的判断: 低

# 金融性格类型
financial_personalities:
  风险厌恶_高_损失厌恶_高_心理账户_高_过度自信_高:
    name: 矛盾型交易者
    description: 您对风险和损失都很敏感，倾向于对不同来源的资金单独管理，但同时又相信自己的判断能力。这种矛盾的组合可能导致您在不同账户上采取截然不同的策略，既保守又激进。
    advice: 建议将资金整合管理，制定统一的投资策略，主要配置货币基金和短债基金，少量配置稳健型混合基金。
  风险厌恶_高_损失厌恶_高_心理账户_高_过度自信_低:
    name: 谨慎守护者
    description: 您非常谨慎对待风险，对损失特别敏感，并且会为不同来源的资金设置不同的心理账户。您不盲目自信，能够认识到市场的不确定性。
    advice: 建议选择低风险的投资产品组合，以货币基金和短债基金为主，降低波动带来的心理负担。
  风险厌恶_高_损失厌恶_高_心理账户_低_过度自信_高:
    name: 固执型保守者
    description: 您虽然追求安全性，对风险和损失都很敏感，但统一管理所有资金，且过度相信自己的判断。这种组合可能导致您在保守投资中过度集中于某些您认为"安全"的资产。
    advice: 建议在稳健产品中也要保持适度分散，配置不同类型的债券基金，辅以小比例的混合型基金。
  风险厌恶_高_损失厌恶_高_心理账户_低_过度自信_低:
    name: 稳健统筹者
    description: 您在投资时非常注重规避风险，对损失高度敏感，但善于统一管理资金，不受资金来源的影响，同时能够客观评估市场与自己的能力。
    advice: 建议选择稳健型投资组合，以短债基金和中长债基金为主，适当配置一些中低风险产品。
  风险厌恶_高_损失厌恶_低_心理账户_高_过度自信_高:
    name: 目标导向型投资者
    description: 您虽然对风险敏感，但能够承受短期损失，喜欢为不同资金设置不同目标，且对自己的投资能力充满信心。这使您能为不同目标采取差异化策略。
    advice: 建议在不同账户中设置明确的投资期限和目标，短期资金配置货币基金，中长期资金可配置债券和少量混合基金。
  风险厌恶_高_损失厌恶_低_心理账户_高_过度自信_低:
    name: 细致分配者
    description: 您倾向于规避投资风险，但对可能的损失有较强的心理承受能力，习惯为不同来源的资金设置不同的投资目标，同时不过度自信。
    advice: 建议利用您的分类思维，针对不同期限的目标选择相应的产品，以债券基金为主，辅以适量混合基金。
  风险厌恶_高_损失厌恶_低_心理账户_低_过度自信_高:
    name: 稳中求变者
    description: 您偏好低风险但能容忍暂时损失，采用统一的资金管理方式，对自己的判断有较强信心。这种组合使您在整体保守的前提下敢于把握特定机会。
    advice: 建议以中长债基金和混合基金为主，适度配置少量股票基金，但要设定严格的止损策略。
  风险厌恶_高_损失厌恶_低_心理账户_低_过度自信_低:
    name: 理性保守者
    description: 您偏好低风险投资但能够理性面对损失，采用统一的资金管理策略，不盲目自信。这种组合使您在保守投资的同时保持了客观冷静的态度。
    advice: 建议选择以短债和中长债基金为主，配置少量混合型基金的均衡投资组合。
  风险厌恶_低_损失厌恶_高_心理账户_高_过度自信_高:
    name: 冲动型冒险家
    description: 您愿意承担高风险，但对损失又十分敏感，喜欢为不同资金设立不同账户，且对自己的判断过度自信。这种矛盾组合可能导致您做出冲动决策。
    advice: 建议制定严格的投资原则和止损点，将冒险资金限制在总资产的小比例内，主要配置混合型和股票型基金。
  风险厌恶_低_损失厌恶_高_心理账户_高_过度自信_低:
    name: 分散型冒险者
    description: 您愿意承担较高的投资风险以追求更高回报，但对损失非常敏感，且倾向于为不同来源的资金设立不同账户。您认识到自己判断的局限性。
    advice: 建议在高风险资产上设定明确的止损策略，同时保留一部分资金在安全资产中作为缓冲。
  风险厌恶_低_损失厌恶_高_心理账户_低_过度自信_高:
    name: 自信型矛盾者
    description: 您乐于接受高风险投资，但对投资损失却相当敏感，统一管理您的资金，且对自己的判断充满信心。这种内在矛盾可能导致投资决策的不一致。
    advice: 建议设置明确的整体风险预算，同时为每次投资设定严格的止损点，避免情绪决策。
  风险厌恶_低_损失厌恶_高_心理账户_低_过度自信_低:
    name: 矛盾型平衡者
    description: 您乐于接受高风险投资，但对投资损失却相当敏感，统一管理您的资金，且能够客观评估自己。这种组合使您在追求收益的同时注重风险管理。
    advice: 建议采用核心卫星策略，以稳健资产为核心，高风险资产为卫星，并设定严格的再平衡机制。
  风险厌恶_低_损失厌恶_低_心理账户_高_过度自信_高:
    name: 激进多账户投资者
    description: 您乐于承担高风险，对损失不太敏感，喜欢为不同资金设立不同账户，且对自己的判断非常自信。这种组合可能导致您在某些账户中承担过度风险。
    advice: 建议即使在不同账户中也要保持适度分散，避免将某个特定账户完全投入高风险资产。
  风险厌恶_低_损失厌恶_低_心理账户_高_过度自信_低:
    name: 灵活多面手
    description: 您不惧怕风险，对损失有较高的容忍度，同时喜欢根据资金来源分别管理，且能够客观评估自己的能力。这种组合使您能够为不同目标灵活制定策略。
    advice: 建议充分利用分类思维的优势，为不同账户设置明确的目标和风险预算，追求整体最优。
  风险厌恶_低_损失厌恶_低_心理账户_低_过度自信_高:
    name: 大胆冒险家
    description: 您乐于承担高风险，对损失不敏感，采用统一的资金管理方式，且对自己的判断充满信心。这种组合使您在投资中非常进取，但可能轻视系统性风险。
    advice: 建议适度关注市场整体风险，即使是激进配置也要保持基本的分散化原则，避免过度集中。
  风险厌恶_低_损失厌恶_低_心理账户_低_过度自信_低:
    name: 理性进取者
    description: 您在投资上表现得进取，愿意承担高风险以追求高回报，对损失有较高的承受能力，采用统一的资金管理方式，且能够客观评估自己的能力。
    advice: 建议配置较高比例的股票型基金和创业板基金，同时合理分散，定期再平衡，控制单一持仓风险。

# 实验分组配置
experiment_groups:
  control:
    name: 控制组
    description: 以下是您之前选择的资产配置
    recommendation_strategy: standard  # 使用标准的均值方差前沿组合
    adjustment: {}  # 不做特殊调整，使用风险评分对应的标准配置
    
  accommodate:
    name: 迎合组
    description: 以下是您之前选择的资产配置，以及系统根据您展示出的金融性格投资偏好推荐的个性化配置。
    recommendation_strategy: accommodate  # 迎合投资者的偏好
    adjustment:
      # 根据投资者偏好调整配置，偏向于投资者的初始选择
      risk_aversion_高:
        风险资产_下调: 0.1  # 下调高风险资产配置10%
        安全资产_上调: 0.1   # 上调低风险资产配置10%
      risk_aversion_低:
        风险资产_上调: 0.1  # 上调高风险资产配置10%
        安全资产_下调: 0.1   # 下调低风险资产配置10%
        
  mental_accounting_education:
    name: 心理账户教育组
    description: 金融性格投资偏好显示，您在心理账户维度存在偏差，可能只考虑单个资产而不是整体投资组合的盈亏做出投资决策。以下是您之前选择的资产配置，以及系统修正您偏差后的推荐配置。
    recommendation_strategy: educate  # 纠正投资者的偏见
    adjustment:
      # 根据心理账户问题调整组合分散度
      心理账户_高:
        分散度_提高: 0.15  # 提高分散度，使资产配置更加平均
        
  loss_aversion_education:
    name: 损失厌恶教育组
    description: 金融性格投资偏好显示，您在损失厌恶维度存在偏差，可能会因为过度在乎损失而导致投资过于保守。以下是您之前选择的资产配置，以及系统修正您偏差后的推荐配置。
    recommendation_strategy: educate  # 纠正投资者的偏见
    adjustment:
      # 根据损失厌恶问题调整风险资产配置
      损失厌恶_高:
        风险资产_上调: 0.2  # 提高风险资产配置，纠正过度保守
        安全资产_下调: 0.2   # 下调安全资产配置
        
# 资产风险类别映射
asset_risk_categories:
  风险资产: ["混合基金-南方成长", "股票基金-易方达上证50", "创业板基金-华夏创业板ETF"]
  安全资产: ["货币基金-余额宝", "短债基金-建信短债", "中长债基金-易方达中债"] 